---
resources:
- name: behaveware
  type: git
  source: {uri: https://github.com/mcnichol/behaveware.git, branch: master }

jobs:
- name: unit
  plan:
  - get: behaveware
    trigger: true
  - task: unit
    file: behaveware/ci/unit/task.yml
